mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
#      logic-delete-value: deleted
#      logic-delete-field: 2
#      logic-not-delete-value: 1
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.demo.pojo
  mapper-locations: classpath:com/demo/mapper/*.xml