spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/store?useServerPrepStmts=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: Aa123456@
  main:
    banner-mode: off
